# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 600)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.X1 = QtWidgets.QPushButton(self.centralwidget)
        self.X1.setGeometry(QtCore.QRect(0, 0, 200, 200))
        self.X1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.X1.setMouseTracking(False)
        self.X1.setStyleSheet("QPushButton {\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #DA48F0, stop:1 #5F006E);\n"
"    border-style: solid;\n"
"    border-width: 2px;\n"
"    border-color: #5F006E;\n"
"    border-radius: 10px;\n"
"    color: #F0ACEB;\n"
"    font-size: 18px;\n"
"    padding: 10px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #D34BED, stop:1 #67004D);\n"
"    border-color: #67004D;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #5F006E;\n"
"    border-color: #5F006E;\n"
"}")
        self.X1.setText("")
        self.X1.setObjectName("X1")
        self.X2 = QtWidgets.QPushButton(self.centralwidget)
        self.X2.setGeometry(QtCore.QRect(200, 0, 200, 200))
        font = QtGui.QFont()
        font.setPointSize(1)
        self.X2.setFont(font)
        self.X2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.X2.setStyleSheet("QPushButton {\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #DA48F0, stop:1 #5F006E);\n"
"    border-style: solid;\n"
"    border-width: 2px;\n"
"    border-color: #5F006E;\n"
"    border-radius: 10px;\n"
"    color: #F0ACEB;\n"
"    font-size: 18px;\n"
"    padding: 10px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #D34BED, stop:1 #67004D);\n"
"    border-color: #67004D;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #5F006E;\n"
"    border-color: #5F006E;\n"
"}")
        self.X2.setText("")
        self.X2.setObjectName("X2")
        self.X3 = QtWidgets.QPushButton(self.centralwidget)
        self.X3.setGeometry(QtCore.QRect(400, 0, 200, 200))
        self.X3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.X3.setStyleSheet("QPushButton {\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #DA48F0, stop:1 #5F006E);\n"
"    border-style: solid;\n"
"    border-width: 2px;\n"
"    border-color: #5F006E;\n"
"    border-radius: 10px;\n"
"    color: #F0ACEB;\n"
"    font-size: 18px;\n"
"    padding: 10px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #D34BED, stop:1 #67004D);\n"
"    border-color: #67004D;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #5F006E;\n"
"    border-color: #5F006E;\n"
"}")
        self.X3.setText("")
        self.X3.setObjectName("X3")
        self.Y1 = QtWidgets.QPushButton(self.centralwidget)
        self.Y1.setGeometry(QtCore.QRect(0, 200, 200, 200))
        self.Y1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Y1.setStyleSheet("QPushButton {\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #DA48F0, stop:1 #5F006E);\n"
"    border-style: solid;\n"
"    border-width: 2px;\n"
"    border-color: #5F006E;\n"
"    border-radius: 10px;\n"
"    color: #F0ACEB;\n"
"    font-size: 18px;\n"
"    padding: 10px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #D34BED, stop:1 #67004D);\n"
"    border-color: #67004D;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #5F006E;\n"
"    border-color: #5F006E;\n"
"}")
        self.Y1.setText("")
        self.Y1.setObjectName("Y1")
        self.Y2 = QtWidgets.QPushButton(self.centralwidget)
        self.Y2.setGeometry(QtCore.QRect(200, 200, 200, 200))
        self.Y2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Y2.setStyleSheet("QPushButton {\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #DA48F0, stop:1 #5F006E);\n"
"    border-style: solid;\n"
"    border-width: 2px;\n"
"    border-color: #5F006E;\n"
"    border-radius: 10px;\n"
"    color: #F0ACEB;\n"
"    font-size: 18px;\n"
"    padding: 10px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #D34BED, stop:1 #67004D);\n"
"    border-color: #67004D;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #5F006E;\n"
"    border-color: #5F006E;\n"
"}")
        self.Y2.setText("")
        self.Y2.setObjectName("Y2")
        self.Y3 = QtWidgets.QPushButton(self.centralwidget)
        self.Y3.setGeometry(QtCore.QRect(400, 200, 200, 200))
        self.Y3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Y3.setStyleSheet("QPushButton {\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #DA48F0, stop:1 #5F006E);\n"
"    border-style: solid;\n"
"    border-width: 2px;\n"
"    border-color: #5F006E;\n"
"    border-radius: 10px;\n"
"    color: #F0ACEB;\n"
"    font-size: 18px;\n"
"    padding: 10px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #D34BED, stop:1 #67004D);\n"
"    border-color: #67004D;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #5F006E;\n"
"    border-color: #5F006E;\n"
"}")
        self.Y3.setText("")
        self.Y3.setObjectName("Y3")
        self.Z1 = QtWidgets.QPushButton(self.centralwidget)
        self.Z1.setGeometry(QtCore.QRect(0, 400, 200, 200))
        self.Z1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Z1.setStyleSheet("QPushButton {\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #DA48F0, stop:1 #5F006E);\n"
"    border-style: solid;\n"
"    border-width: 2px;\n"
"    border-color: #5F006E;\n"
"    border-radius: 10px;\n"
"    color: #F0ACEB;\n"
"    font-size: 18px;\n"
"    padding: 10px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #D34BED, stop:1 #67004D);\n"
"    border-color: #67004D;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #5F006E;\n"
"    border-color: #5F006E;\n"
"}")
        self.Z1.setText("")
        self.Z1.setObjectName("Z1")
        self.Z2 = QtWidgets.QPushButton(self.centralwidget)
        self.Z2.setGeometry(QtCore.QRect(200, 400, 200, 200))
        self.Z2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Z2.setStyleSheet("QPushButton {\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #DA48F0, stop:1 #5F006E);\n"
"    border-style: solid;\n"
"    border-width: 2px;\n"
"    border-color: #5F006E;\n"
"    border-radius: 10px;\n"
"    color: #F0ACEB;\n"
"    font-size: 18px;\n"
"    padding: 10px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #D34BED, stop:1 #67004D);\n"
"    border-color: #67004D;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #5F006E;\n"
"    border-color: #5F006E;\n"
"}")
        self.Z2.setText("")
        self.Z2.setObjectName("Z2")
        self.Z3 = QtWidgets.QPushButton(self.centralwidget)
        self.Z3.setGeometry(QtCore.QRect(400, 400, 200, 200))
        self.Z3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Z3.setStyleSheet("QPushButton {\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #DA48F0, stop:1 #5F006E);\n"
"    border-style: solid;\n"
"    border-width: 2px;\n"
"    border-color: #5F006E;\n"
"    border-radius: 10px;\n"
"    color: #F0ACEB;\n"
"    font-size: 18px;\n"
"    padding: 10px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #D34BED, stop:1 #67004D);\n"
"    border-color: #67004D;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #5F006E;\n"
"    border-color: #5F006E;\n"
"}")
        self.Z3.setText("")
        self.Z3.setObjectName("Z3")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 600, 600))
        self.frame.setStyleSheet("background-color: #F04894\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frame.raise_()
        self.X1.raise_()
        self.X2.raise_()
        self.X3.raise_()
        self.Y1.raise_()
        self.Y2.raise_()
        self.Y3.raise_()
        self.Z1.raise_()
        self.Z2.raise_()
        self.Z3.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
