# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(750, 600)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.X1 = QtWidgets.QPushButton(self.centralwidget)
        self.X1.setGeometry(QtCore.QRect(0, 0, 200, 200))
        font = QtGui.QFont()
        font.setFamily("Base 05")
        font.setPointSize(-1)
        self.X1.setFont(font)
        self.X1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.X1.setMouseTracking(False)
        self.X1.setToolTipDuration(1)
        self.X1.setStyleSheet("QPushButton {\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:0.5, x2:1, y2:1, stop:0 #1A1E26, stop:1 #5D75A6);\n"
"    border-style: solid;\n"
"    border-width: 2px;\n"
"    border-color: #5D75A6;\n"
"    border-radius: 10px;\n"
"    color: #F0ACEB;\n"
"    font-size: 60px;\n"
"    padding: 10px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #5D75A6;\n"
"    border-color: #283040;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #283040;\n"
"    border-color: #5F006E;\n"
"}")
        self.X1.setText("")
        self.X1.setObjectName("X1")
        self.X2 = QtWidgets.QPushButton(self.centralwidget)
        self.X2.setGeometry(QtCore.QRect(200, 0, 200, 200))
        font = QtGui.QFont()
        font.setFamily("Base 05")
        font.setPointSize(-1)
        self.X2.setFont(font)
        self.X2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.X2.setToolTipDuration(1)
        self.X2.setStyleSheet("QPushButton {\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #1A1E26, stop:1 #5D75A6);\n"
"    border-style: solid;\n"
"    border-width: 2px;\n"
"    border-color: #5D75A6;\n"
"    border-radius: 10px;\n"
"    color: #F0ACEB;\n"
"    font-size: 60px;\n"
"    padding: 10px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #5D75A6;\n"
"    border-color: #283040;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #283040;\n"
"    border-color: #5F006E;\n"
"}")
        self.X2.setText("")
        self.X2.setObjectName("X2")
        self.X3 = QtWidgets.QPushButton(self.centralwidget)
        self.X3.setGeometry(QtCore.QRect(400, 0, 200, 200))
        font = QtGui.QFont()
        font.setFamily("Base 05")
        font.setPointSize(-1)
        self.X3.setFont(font)
        self.X3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.X3.setToolTipDuration(1)
        self.X3.setStyleSheet("QPushButton {\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:0.5, x2:0, y2:1, stop:0 #1A1E26, stop:1 #5D75A6);\n"
"    border-style: solid;\n"
"    border-width: 2px;\n"
"    border-color: #5D75A6;\n"
"    border-radius: 10px;\n"
"    color: #F0ACEB;\n"
"    font-size: 60px;\n"
"    padding: 10px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #5D75A6;\n"
"    border-color: #283040;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #283040;\n"
"    border-color: #5F006E;\n"
"}")
        self.X3.setText("")
        self.X3.setObjectName("X3")
        self.Y1 = QtWidgets.QPushButton(self.centralwidget)
        self.Y1.setGeometry(QtCore.QRect(0, 200, 200, 200))
        font = QtGui.QFont()
        font.setFamily("Base 05")
        font.setPointSize(-1)
        self.Y1.setFont(font)
        self.Y1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Y1.setToolTipDuration(1)
        self.Y1.setStyleSheet("QPushButton {\n"
"    background-color: qlineargradient(x0:1, y1:2, x2:1, y2:2, stop:0 #1A1E26, stop:1 #5D75A6);\n"
"    border-style: solid;\n"
"    border-width: 2px;\n"
"    border-color: #5D75A6;\n"
"    border-radius: 10px;\n"
"    color: #F0ACEB;\n"
"    font-size: 60px;\n"
"    padding: 10px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #5D75A6;\n"
"    border-color: #283040;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #283040;\n"
"    border-color: #5F006E;\n"
"}")
        self.Y1.setText("")
        self.Y1.setObjectName("Y1")
        self.Y2 = QtWidgets.QPushButton(self.centralwidget)
        self.Y2.setGeometry(QtCore.QRect(200, 200, 200, 200))
        font = QtGui.QFont()
        font.setFamily("Base 05")
        font.setPointSize(-1)
        self.Y2.setFont(font)
        self.Y2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Y2.setToolTipDuration(1)
        self.Y2.setStyleSheet("QPushButton {\n"
"    background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.494, stop:0 #1A1E26 , stop:1 #5D75A6);\n"
"    border-style: solid;\n"
"    border-width: 2px;\n"
"    border-color: #5D75A6;\n"
"    border-radius: 10px;\n"
"    color: #F0ACEB;\n"
"    font-size: 60px;\n"
"    padding: 10px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #5D75A6;\n"
"    border-color: #283040;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #283040;\n"
"    border-color: #5F006E;\n"
"}")
        self.Y2.setText("")
        self.Y2.setObjectName("Y2")
        self.Y3 = QtWidgets.QPushButton(self.centralwidget)
        self.Y3.setGeometry(QtCore.QRect(400, 200, 200, 200))
        font = QtGui.QFont()
        font.setFamily("Base 05")
        font.setPointSize(-1)
        self.Y3.setFont(font)
        self.Y3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Y3.setToolTipDuration(1)
        self.Y3.setStyleSheet("QPushButton {\n"
"    background-color: qlineargradient(x0 : 1, y0 : 1, x1 : 1, y0 : 1, stop:0 #1A1E26, stop:1 #5D75A6);\n"
"    border-style: solid;\n"
"    border-width: 2px;\n"
"    border-color: #5D75A6;\n"
"    border-radius: 10px;\n"
"    color: #F0ACEB;\n"
"    font-size: 60px;\n"
"    padding: 10px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #5D75A6;\n"
"    border-color: #283040;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #283040;\n"
"    border-color: #5F006E;\n"
"}")
        self.Y3.setText("")
        self.Y3.setObjectName("Y3")
        self.Z1 = QtWidgets.QPushButton(self.centralwidget)
        self.Z1.setGeometry(QtCore.QRect(0, 400, 200, 200))
        font = QtGui.QFont()
        font.setFamily("Base 05")
        font.setPointSize(-1)
        self.Z1.setFont(font)
        self.Z1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Z1.setToolTipDuration(1)
        self.Z1.setStyleSheet("QPushButton {\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:0.5, x2:1, y2:0, stop:0 #1A1E26 , stop:1 #5D75A6);\n"
"    border-style: solid;\n"
"    border-width: 2px;\n"
"    border-color: #5D75A6;\n"
"    border-radius: 10px;\n"
"    color: #F0ACEB;\n"
"    font-size: 60px;\n"
"    padding: 10px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #5D75A6;\n"
"    border-color: #283040;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #283040;\n"
"    border-color: #5F006E;\n"
"}")
        self.Z1.setText("")
        self.Z1.setObjectName("Z1")
        self.Z2 = QtWidgets.QPushButton(self.centralwidget)
        self.Z2.setGeometry(QtCore.QRect(200, 400, 200, 200))
        font = QtGui.QFont()
        font.setFamily("Base 05")
        font.setPointSize(-1)
        self.Z2.setFont(font)
        self.Z2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Z2.setToolTipDuration(1)
        self.Z2.setStyleSheet("QPushButton {\n"
"    background-color: qlineargradient(x1:0, y1:1, x2:0, y2:0, stop:0 #1A1E26, stop:1 #5D75A6);\n"
"    border-style: solid;\n"
"    border-width: 2px;\n"
"    border-color: #5D75A6;\n"
"    border-radius: 10px;\n"
"    color: #F0ACEB;\n"
"    font-size: 60px;\n"
"    padding: 10px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #5D75A6;\n"
"    border-color: #283040;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #283040;\n"
"    border-color: #5F006E;\n"
"}")
        self.Z2.setText("")
        self.Z2.setObjectName("Z2")
        self.Z3 = QtWidgets.QPushButton(self.centralwidget)
        self.Z3.setGeometry(QtCore.QRect(400, 400, 200, 200))
        font = QtGui.QFont()
        font.setFamily("Base 05")
        font.setPointSize(-1)
        self.Z3.setFont(font)
        self.Z3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Z3.setToolTipDuration(1)
        self.Z3.setAutoFillBackground(False)
        self.Z3.setStyleSheet("QPushButton {\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:0.5, x2:0, y2:0, stop:0 #1A1E26, stop:1 #5D75A6 );\n"
"    border-style: solid;\n"
"    border-width: 2px;\n"
"    border-color: #5D75A6;\n"
"    border-radius: 10px;\n"
"    color: #F0ACEB;\n"
"    font-size: 60px;\n"
"    padding: 10px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #5D75A6;\n"
"    border-color: #283040;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #283040;\n"
"    border-color: #5F006E;\n"
"}")
        self.Z3.setText("")
        self.Z3.setObjectName("Z3")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 751, 600))
        self.frame.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.frame.setStyleSheet("background-color: #5D75A6\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.b_restart = QtWidgets.QPushButton(self.frame)
        self.b_restart.setGeometry(QtCore.QRect(630, 40, 81, 521))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b_restart.sizePolicy().hasHeightForWidth())
        self.b_restart.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Base 05")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.b_restart.setFont(font)
        self.b_restart.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.b_restart.setToolTip("")
        self.b_restart.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.b_restart.setAutoFillBackground(False)
        self.b_restart.setStyleSheet("QPushButton {\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:0.5, x2:0, y2:1, stop:0 #1A1E26, stop:1 #5D75A6);\n"
"    border-style: solid;\n"
"    border-width: 2px;\n"
"    border-color: #5D75A6;\n"
"    border-radius: 10px;\n"
"    color: #F0ACEB;\n"
"    font-size: 60px;\n"
"    padding: 10px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #5D75A6;\n"
"    border-color: #283040;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #283040;\n"
"    border-color: #5F006E;\n"
"}")
        self.b_restart.setCheckable(False)
        self.b_restart.setObjectName("b_restart")
        self.frame.raise_()
        self.X1.raise_()
        self.X2.raise_()
        self.X3.raise_()
        self.Y1.raise_()
        self.Y2.raise_()
        self.Y3.raise_()
        self.Z1.raise_()
        self.Z2.raise_()
        self.Z3.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.b_restart.setText(_translate("MainWindow", "R\n"
"e\n"
"s\n"
"t\n"
"a\n"
"r\n"
"t"))
